/**
 * 3 default preset configuraties voor nieuwe users.
 * Worden lazy geseeded bij eerste GET /slider-presets.
 */
export const DEFAULT_PRESETS = Object.freeze([
  {
    name: "Balanced",
    sliders: {
      rock: 1.0,
      pop: 1.0,
      electronic: 1.0,
      "hip-hop": 1.0,
      "r&b": 1.0,
      jazz: 1.0,
      classical: 1.0,
      metal: 1.0,
      folk: 1.0,
      country: 1.0,
      blues: 1.0,
      punk: 1.0,
      indie: 1.0,
      soul: 1.0,
      reggae: 1.0,
      latin: 1.0,
      funk: 1.0,
      ambient: 1.0,
      dance: 1.0,
      world: 1.0,
    },
    locked: [],
  },
  {
    name: "Chill Vibes",
    sliders: {
      rock: 0.3,
      pop: 0.6,
      electronic: 0.7,
      "hip-hop": 0.4,
      "r&b": 0.8,
      jazz: 0.9,
      classical: 0.8,
      metal: 0.1,
      folk: 0.7,
      country: 0.4,
      blues: 0.7,
      punk: 0.1,
      indie: 0.6,
      soul: 0.9,
      reggae: 0.8,
      latin: 0.5,
      funk: 0.6,
      ambient: 1.0,
      dance: 0.3,
      world: 0.6,
    },
    locked: [],
  },
  {
    name: "High Energy",
    sliders: {
      rock: 1.0,
      pop: 0.8,
      electronic: 1.0,
      "hip-hop": 0.9,
      "r&b": 0.5,
      jazz: 0.2,
      classical: 0.1,
      metal: 1.0,
      folk: 0.2,
      country: 0.3,
      blues: 0.3,
      punk: 1.0,
      indie: 0.6,
      soul: 0.4,
      reggae: 0.3,
      latin: 0.7,
      funk: 0.8,
      ambient: 0.1,
      dance: 1.0,
      world: 0.4,
    },
    locked: [],
  },
]);
